# Generated by Django 5.2.6 on 2026-04-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0023_userprofile_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='last_price_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
