# Generated by Django 5.2.6 on 2026-04-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oil_logic', '0024_oil_last_price_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='oil',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
